init5
0srnty/geekshop pull request #5
Opened 2021-03-11 08:18 UTC by 0srnty

2021-03-11 09:47 UTC, Vokler requested changes

2021-03-11 09:47 UTC, Vokler commented on basketapp/views.py
> +    content = {}
Почему у вас тут не удаляется объект из БД?

2021-03-12 08:32 UTC, 0srnty commented on basketapp/views.py
> +    content = {}
исправил

2021-03-12 09:28 UTC, Vokler approved these changes

2021-03-12 09:28 UTC, merged